# Generated by Django 3.1.6 on 2021-02-07 21:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210207_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
